name: Generate Project Cards
on:
  schedule:
    - cron: "0 0 1,14,28 * *" 
      timezone: "Europe/Warsaw"
    
  workflow_dispatch: # Manual control

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Cards
        run: |
          # Karta 1
          curl "https://github-readme-stats.vercel.app/api/pin/?username=Tajgero&repo=ideal-pancake&theme=apprentice" -o card-ideal-pancake.svg
          # Karta 2
          curl "https://github-readme-stats.vercel.app/api/pin/?username=Tajgero&repo=Pattern-recognition&theme=apprentice" -o card-pattern-recognition.svg
          # Karta 3
          curl "https://github-readme-stats.vercel.app/api/pin/?username=siemania&repo=mgr_AM_JL&theme=apprentice" -o card-mgr.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add *.svg
          git commit -m "Update GitHub Stats Cards" || exit 0
          git push
