name: Generate Project Cards
on:
  schedule:
    - cron: "0 0 * * *" 
      timezone: "Europe/Warsaw"
    
  workflow_dispatch: # Manual control

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Card 1
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: card-ideal-pancake.svg
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 1
          plugin_repositories_featured: Tajgero/ideal-pancake # Repo
          config_timezone: Europe/Warsaw

      - name: Generate Card 2
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: card-pattern-recognition.svg
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 1
          plugin_repositories_featured: Tajgero/Pattern-recognition # Repo

      - name: Generate Card 3
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: card-mgr.svg
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 1
          plugin_repositories_featured: siemania/mgr_AM_JL # Repo
